name: Static Analysis

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/static-analysis.yml"
      - "examples/**"
      - "python/**"
      - "tests/**"
      - "typings/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - ".github/workflows/static-analysis.yml"
      - "examples/**"
      - "python/**"
      - "tests/**"
      - "typings/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --only-dev

      - name: Ruff lint
        run: uv run --no-sync ruff check .

      - name: Ruff format
        run: uv run --no-sync ruff format --diff .

  typecheck:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --group examples

      - name: Run mypy
        run: uv run mypy python tests examples
