name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --only-dev

      - name: Ruff lint
        run: uv run --no-sync ruff check .

      - name: Ruff format
        run: uv run --no-sync ruff format --diff .

  typecheck:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --group examples

      - name: Run mypy
        run: uv run mypy python tests examples

  test:
    name: Test
    needs: [lint, typecheck]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
        torch-version: ["2.7.*", "2.8.*", "2.9.*"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install specified PyTorch version
        run: uv add "torch==${{ matrix.torch-version }}"

      - name: Run tests
        run: uv run pytest tests
